### ISSUE TITLE
도커파일 삽입

### ISSUE THREAD

**Issue by fkthfvk112** [emartFresh/emart-fresh-front#1]
## Description 🗞️📕
프론트엔드 리액트 코드를 nginx위에 띄우는 도커파일 생성

## To-Do ✔️
- [x] 도커 이미지 빌드
- [x] 도커 이미지 도커 허브 push
- [x] 도커 이미지 기반 컨테이너 작동 확인

## notes 📝
- 이미지 다운로드
  - docker pull fkthfvk112/front-end
