### ISSUE TITLE
[Feature: 이벤트 리스트 Navbar 진행중&종료된 이벤트 컴포넌트 변경]

### ISSUE THREAD

**Issue by 7memoria7** [emartFresh/emart-fresh-front#10]
## Page 🖥️
EventList.tsx
EventOngoing.tsx
EventEnded.tsx
EvnetList.module.css

## To-Do ✔️
- [x] 이벤트 리스트 페이지 NavBar 이벤트 진행 중 클릭 시 컴포넌트 변경
- [x] 이벤트 리스트 페이지 NavBar 종료된 이벤트 클릭 시 컴포넌트 변경
- [x] 종료된 이벤트 이미지 CSS 추가 수정
- [x] 백엔드와 데이터 통신
