### ISSUE TITLE
[Feature] 홈페이지 반응형 디자인 작업

### ISSUE THREAD

**Issue by fkthfvk112** [emartFresh/emart-fresh-front#144]
## Description 🗞️📕
홈페이지 반응형 디자인 작업을 한다.

## Page 🖥️
홈페이지

## To-Do ✔️
- [x] 이벤트 스와이퍼 반응형 디자인
- [x] 아이템 스와이퍼 반응형 디자인
- [x] 이미 받은 쿠폰 디자인
- [x] 쿠폰 컨테이너 반응형 디자인
