### ISSUE TITLE
이벤트 등록페이지  이미지 미리보기

### ISSUE THREAD

**Issue by 7memoria7** [emartFresh/emart-fresh-front#42]
## Page 🖥️
EventUpdate.tsx
## To-Do ✔️
- [x] 이벤트 등록페이지 이미지 등록 시 이미지 미리보기
- [x] 배너이미지와 상세이미지 UI 구현
- [x] 추가 작업: 파일업로드-> 이미지파일로 바꾸기
- [x] 배너/상세이미지 등록하면 파일업로드 이미지는 사라지게 만들기
