### ISSUE TITLE
[BUG] 결제 오류

### ISSUE THREAD

**Issue by fkthfvk112** [emartFresh/emart-fresh-front#62]
## Describe the bug 🐞

외부 결제 시스템과 연동된 결제 기능의 API 기능 오류 발생 및 기능 추가 필요.

결제 완료시 장바구니 비우기 기능 추가

## Screen Shot or Error Message 📸
```
userUtils.ts:47     GET http://localhost:8080/cart/decreaseCartProduct 405 (Method Not Allowed)
```

## To-Do ✔️
- [ ] API 연동 수정
- [ ] API success후 장바구니 비우기 기능 추가 (백에서 연동해서 처리)
- [ ] 모든 과정이 200을 뱉으면 페이지 데이터 리로드(장바구니 비워진 것을 보여주기)
