### ISSUE TITLE
이벤트리스트 ui작업

### ISSUE THREAD

**Issue by 7memoria7** [emartFresh/emart-fresh-front#7]
## Page 🖥️
EventList.tsx

## To-Do ✔️
- [x] 이벤트 페이지에서 이벤트 리스트를 보여주는 ui 작업
- [x] 이벤트 리스트 마우스 호버시 이미지확대 및 텍스트 노란색으로 바뀜
- [x] 이벤트 Navbar 진행중인 이벤트 & 진행완료 이벤트 ui작업
